### ISSUE TITLE
Error with Relative path in css file when compiling

### ISSUE THREAD

**Issue by gbozee** [insin/nwb#232]
This issue is a: 

- [ ] Bug report
- [ ] Feature request
- [X] Question / support request
- [ ] Other

I just started using nwb and am in the process of migrating a previus create-react-app project to it.

I am not sure how to fix relative file path in a css and when compiling, I get errors. attached is a screenshot
![image](https://cloud.githubusercontent.com/assets/1777544/21965553/c42af7a2-db62-11e6-90bb-b919728b4522.png)

Is there a way to resolve this by overriding the `postcss` or through any other means? I saw this issue https://github.com/postcss/postcss-loader/issues/53 but I am not sure how to proceed. Any help would be appreciated.

**Comment by insin** [comment]
Tried to repro this with nwb v0.14.1 based on your screenshot, but I couldn't with this directory layout and CSS (being imported from `src/index.js`):

![sublime_text_2017-01-16_07-04-53](https://cloud.githubusercontent.com/assets/226692/21966176/3879d6d0-dbba-11e6-8a8d-255bc898a137.png)
```css
@font-face {
  font-family: 'FontAwesome';
  src: url('../fonts/fontawesome-webfont.eot?v=4.7.0');
  src: url('../fonts/fontawesome-webfont.eot?#iefix&v=4.7.0') format('embedded-opentype'), url('../fonts/fontawesome-webfont.woff2?v=4.7.0') format('woff2'), url('../fonts/fontawesome-webfont.woff?v=4.7.0') format('woff'), url('../fonts/fontawesome-webfont.ttf?v=4.7.0') format('truetype'), url('../fonts/fontawesome-webfont.svg?v=4.7.0#fontawesomeregular') format('svg');
  font-weight: normal;
  font-style: normal;
}
```

- What does your directory layout under `src/` look like?
- Could you provide a sample of the the CSS file which is trying to reference the font?
- Is `hireplace-styles.css` being directly imported by a JavaScript module or `@import` ed from another CSS file?
